const Subjects = [
  { id: 1, label: "Control System", major: "Computer System Engineering " },
  { id: 2, label: "Operating Systems", major: "Computer System Engineering " },
  {
    id: 3,
    label: "Microproccessor Systems And Applications",
    major: "Computer System Engineering ",
  },
  { id: 4, label: "Electronics 1", major: "Engineering " },
  { id: 5, label: "Electronics 2", major: "Engineering " },
  { id: 6, label: "C++ 1", major: "EIT " },
  { id: 7, label: "C++ 2", major: "EIT " },
  { id: 8, label: "Probability and Random Variables", major: "Engineering" },
  {
    id: 9,
    label: "Signals and Systems",
    major: "Engineering ",
  },
  { id: 10, label: "Machine Learning", major: "Computer System Engineering " },
  {
    id: 11,
    label: "Artificial Intelligence (Engineering) ",
    major: "Computer System Engineering ",
  },
  {
    id: 12,
    label: "Engineering Drawing",
    major: "Engineering",
  },
  {
    id: 13,
    label: "Numerical Methods",
    major: "Engineering ",
  },
  { id: 14, label: "General Physics 1", major: "Engineering " },
  { id: 15, label: "General Physics 2", major: "Engineering " },
  { id: 16, label: "Statics", major: "Engineering " },
  {
    id: 17,
    label: "Mobile Programming (Engineering)",
    major: "Computer System Engineering ",
  },
  {
    id: 18,
    label: "Introduction To Database Systems (Engineering)",
    major: "Computer System Engineering ",
  },
  { id: 19, label: "Data Structures", major: "EIT " },
  {
    id: 20,
    label: "Digital Logic Design (Engineering)",
    major: "Engineering ",
  },
  {
    id: 21,
    label: "Advanced Digital Systems Design",
    major: "Computer System Engineering ",
  },
  { id: 22, label: "Calculus 1", major: "Engineering " },
  { id: 23, label: "Calculus 2", major: "Engineering " },
  { id: 24, label: "Electrical Circuits 1", major: "Engineering " },
  { id: 25, label: "Electrical Circuits 2", major: "Engineering " },
  { id: 26, label: "Discrete Mathmatics", major: "Engineering " },
  { id: 27, label: "Engineering Mathmatics 1", major: "Engineering" },
  { id: 28, label: "Engineering Mathmatics 2", major: "Engineering" },
  {
    id: 29,
    label: "Computer Organization",
    major: "Computer System Engineering ",
  },
  { id: 30, label: "Physics Lab", major: "Engineering " },
  { id: 31, label: "Technical Writing", major: "Engineering " },
  {
    id: 32,
    label: "Selected Programming",
    major: "Computer System Engineering ",
  },
  { id: 33, label: "C++ 1 Lab", major: "EIT" },
  { id: 34, label: "Embbeded Systems", major: "Computer System Engineering " },
  { id: 35, label: "Electronics Lab", major: "Engineering " },
  { id: 36, label: "Electrical Circuits Lab", major: "Engineering " },
  {
    id: 37,
    label: "Digital Logic Design Lab",
    major: "Computer System Engineering ",
  },
  { id: 38, label: "Linux Lab", major: "Computer System Engineering " },
  { id: 39, label: "Workshop 1", major: "Computer System Engineering " },
  { id: 40, label: "Workshop 2", major: "Computer System Engineering " },
  { id: 41, label: "Engineering Project Management", major: "Engineering " },
  { id: 42, label: "Principles Of Object Oriented Programming", major: "EIT " },
  {
    id: 43,
    label: "Algorithms Analysis And Design",
    major: "Computer System Engineering ",
  },
  {
    id: 44,
    label: "Data And Computer Networks",
    major: "Computer System Engineering ",
  },
  {
    id: 45,
    label: "Microprocessor Lab",
    major: "Computer System Engineering ",
  },
  {
    id: 46,
    label: "Computer Network Lab",
    major: "Computer System Engineering ",
  },
  {
    id: 47,
    label: "Software Engineering (Engineering)",
    major: "Computer System Engineering ",
  },
  {
    id: 48,
    label: "Assembly Programming Lab",
    major: "Computer System Engineering ",
  },
  {
    id: 49,
    label: "Embedded Systems Lab",
    major: "Computer System Engineering ",
  },
  {
    id: 50,
    label: "Database Lab (Engineering)",
    major: "Computer System Engineering ",
  },
  {
    id: 51,
    label: "Web Programming",
    major: "Computer System Engineering ",
  },
];

export default Subjects;
