const Subjects = [
  { id: 1, label: "Control System", major: "Computer system engineering " },
  { id: 2, label: "Operating System", major: "Computer system engineering " },
  { id: 3, label: "Microproccessor", major: "Computer system engineering " },
  { id: 4, label: "Electronics 1", major: "Computer system engineering " },
  { id: 5, label: "Electronics 2", major: "Computer system engineering " },
  { id: 6, label: "C++ 1", major: "Computer system engineering " },
  { id: 7, label: "C++ 2", major: "Computer system engineering " },
  { id: 8, label: "Random", major: "Computer system engineering " },
  {
    id: 9,
    label: "Signals and Systems",
    major: "Computer system engineering ",
  },
  { id: 10, label: "Machine Learning", major: "Computer system engineering " },
  { id: 11, label: "AI", major: "Computer system engineering " },
  {
    id: 12,
    label: "Engineering Drawing",
    major: "Computer system engineering ",
  },
  { id: 13, label: "Numerical Methods", major: "Computer system engineering " },
  { id: 14, label: "Physics 1", major: "Computer system engineering " },
  { id: 15, label: "Physics 2", major: "Computer system engineering " },
  { id: 16, label: "Statics", major: "Computer system engineering " },
  {
    id: 17,
    label: "Mobile Programming",
    major: "Computer system engineering ",
  },
  { id: 18, label: "Database", major: "Computer system engineering " },
  { id: 19, label: "Data Structures", major: "Computer system engineering " },
  { id: 20, label: "Digital", major: "Computer system engineering " },
  { id: 21, label: "Advanced Digital", major: "Computer system engineering " },
  { id: 22, label: "Calculus 1", major: "Computer system engineering " },
  { id: 23, label: "Calculus 2", major: "Computer system engineering " },
  { id: 24, label: "Circuit 1", major: "Computer system engineering " },
  { id: 25, label: "Circuit 2", major: "Computer system engineering " },
  { id: 26, label: "Discrete", major: "Computer system engineering " },
  { id: 27, label: "Math 1", major: "Computer system engineering " },
  { id: 28, label: "Math 2", major: "Computer system engineering " },
  {
    id: 29,
    label: "Computer Organization",
    major: "Computer system engineering ",
  },
  { id: 30, label: "Physics Lab", major: "Computer system engineering " },
  { id: 31, label: "Technical", major: "Computer system engineering " },
  {
    id: 32,
    label: "Selected Programming",
    major: "Computer system engineering ",
  },
  { id: 33, label: "C++ 1 Lab", major: "Computer system engineering " },
  { id: 34, label: "Embbeded", major: "Computer system engineering " },
  { id: 35, label: "Electronics Lab", major: "Computer system engineering " },
  { id: 36, label: "Circuit Lab", major: "Computer system engineering " },
  { id: 37, label: "Digital Lab", major: "Computer system engineering " },
  { id: 38, label: "Linux Lab", major: "Computer system engineering " },
  { id: 39, label: "Workshop 1", major: "Computer system engineering " },
  { id: 40, label: "Workshop 2", major: "Computer system engineering " },
];

export default Subjects;
